from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path
from typing import Any
from uuid import uuid4

import jwt
from cryptography.hazmat.primitives import serialization

from app.services.trust_registry import (
    TRANSPARENCY_CHECKPOINT_VERSION,
    TRANSPARENCY_ENTRY_VERSION,
    transparency_leaf_hash,
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create development-only trust registry and transparency requests."
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--private-key", type=Path, required=True)
    parser.add_argument("--jwks", type=Path, required=True)
    parser.add_argument("--key-id", default="model-atlas-demo-2026")
    parser.add_argument("--publisher-issuer", default="model-atlas-demo-publisher")
    parser.add_argument("--collector-issuer", default="model-atlas-demo-collector")
    parser.add_argument("--log-issuer", default="model-atlas-demo-transparency")
    parser.add_argument("--supply-chain-attestation-id", required=True)
    parser.add_argument("--supply-chain-attestation-hash", required=True)
    parser.add_argument("--statement-id", required=True)
    parser.add_argument("--subject-digest", required=True)
    args = parser.parse_args()

    summary = create_bundle(args)
    print(json.dumps(summary, indent=2, sort_keys=True))


def create_bundle(args: argparse.Namespace) -> dict[str, Any]:
    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    private_key = serialization.load_pem_private_key(
        args.private_key.read_bytes(),
        password=None,
    )
    jwks = json.loads(args.jwks.read_text(encoding="utf-8"))
    keys = jwks.get("keys") if isinstance(jwks, dict) else None
    matching = [
        key
        for key in keys or []
        if isinstance(key, dict) and key.get("kid") == args.key_id
    ]
    if len(matching) != 1:
        raise ValueError("JWKS must contain exactly one matching public key")
    public_jwk = dict(matching[0])
    root_requests = {
        "publisher": _root_request(
            name="Model Atlas demo publisher",
            purpose="model_publisher",
            issuer=args.publisher_issuer,
            key_id=args.key_id,
            public_jwk=public_jwk,
        ),
        "collector": _root_request(
            name="Model Atlas demo collector",
            purpose="production_collector",
            issuer=args.collector_issuer,
            key_id=args.key_id,
            public_jwk=public_jwk,
        ),
        "transparency": _root_request(
            name="Model Atlas demo transparency log",
            purpose="transparency_log",
            issuer=args.log_issuer,
            key_id=args.key_id,
            public_jwk=public_jwk,
        ),
    }
    root_paths: dict[str, str] = {}
    for label, request in root_requests.items():
        path = output_dir / f"trust-root-{label}-request.json"
        _write_json(path, request)
        root_paths[label] = str(path)

    entry = {
        "schema_version": TRANSPARENCY_ENTRY_VERSION,
        "supply_chain_attestation_id": args.supply_chain_attestation_id,
        "attestation_hash": args.supply_chain_attestation_hash,
        "statement_id": args.statement_id,
        "subject_digest": args.subject_digest,
    }
    leaf_hash = transparency_leaf_hash(entry)
    claims = {
        "iss": args.log_issuer,
        "iat": int(dt.datetime.now(dt.UTC).timestamp()),
        "jti": f"model-transparency-proof-{uuid4()}",
        "schema_version": TRANSPARENCY_CHECKPOINT_VERSION,
        "log_id": args.log_issuer,
        "tree_size": 1,
        "root_hash": leaf_hash,
        "leaf_hash": leaf_hash,
        "integrated_at": dt.datetime.now(dt.UTC).replace(microsecond=0).isoformat(),
    }
    checkpoint_jws = jwt.encode(
        claims,
        private_key,
        algorithm=str(public_jwk.get("alg") or "RS256"),
        headers={"kid": args.key_id},
    )
    proof_request_path = output_dir / "transparency-proof-request.json"
    _write_json(
        proof_request_path,
        {
            "supply_chain_attestation_id": args.supply_chain_attestation_id,
            "signed_checkpoint_jws": checkpoint_jws,
            "entry_json": entry,
            "log_index": 0,
            "inclusion_path": [],
            "notes": "Development-only transparency evidence generated by Model Atlas.",
        },
    )
    return {
        "trust_root_request_paths": root_paths,
        "transparency_proof_request_path": str(proof_request_path),
        "proof_id": claims["jti"],
        "leaf_hash": leaf_hash,
        "trust_tier": "development",
        "production_eligible": False,
    }


def _root_request(
    *,
    name: str,
    purpose: str,
    issuer: str,
    key_id: str,
    public_jwk: dict[str, Any],
) -> dict[str, Any]:
    return {
        "name": name,
        "purpose": purpose,
        "issuer": issuer,
        "key_id": key_id,
        "algorithm": str(public_jwk.get("alg") or "RS256"),
        "public_key_jwk_json": public_jwk,
        "trust_tier": "development",
        "source_type": "development",
        "source_uri": None,
        "notes": "Development-only trust root; not valid for production eligibility.",
    }


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
